### ISSUE TITLE
ImportError: cannot import name 'EdgeSoftmax'

### ISSUE THREAD

**Issue by zhilingz** [lgalke/gnn-pretraining-evaluation#1]
hi, I've been plagued by this problem for a long time, and when I follow the README.md, the code goes wrong.
My Environment:
Linux version 3.10.0-957.10.1.el7.x86_64
torch.__version__='1.6.0+cu101'
dgl.__version__='0.1.3'

Thanks!

**Comment by lgalke** [comment]
Hey, so is this resolved?
